#!/usr/bin/env python3
"""Describe the published Swara Studio data: the shape of every file.

    python3 scripts/carnatic/describe_data.py <data-dir> > docs/carnatic/DATA-SCHEMA.md

Reads the files scripts/sync-carnatic-data.sh publishes (a local build of
them, e.g. `build_data.py <research> <dir>`) and writes each file's shape as
TypeScript-like types: every key, `?` where not every object has it, and the
union of the types seen. Field names and types only; no research content is
copied. Rerun it whenever the build changes what it writes, and commit the
result with that change.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

FILES = ["ragas.json", "talas.json", "lessons.json", "instruments.json", "featured.json", "gamakas.json"]


def kind(v) -> str:
    return {dict: "object", list: "array", str: "string", int: "int", float: "number",
            bool: "bool", type(None): "null"}[type(v)]


def looks_like_a_map(objs: list[dict], keys: list[str]) -> bool:
    """Keys that are data (swara names, ids, numbers) rather than field names."""
    if len(keys) <= 14:
        return False
    fieldlike = sum(1 for k in keys if re.match(r"^[a-z][a-zA-Z0-9_]*$", k))
    return fieldlike < len(keys) / 2


def render(vals: list, ind: int) -> str:
    kinds = {kind(v) for v in vals}
    parts = sorted(kinds - {"object", "array"})
    objs = [v for v in vals if isinstance(v, dict)]
    arrs = [v for v in vals if isinstance(v, list)]
    if objs:
        keys: list[str] = []
        for o in objs:
            for k in o:
                if k not in keys:
                    keys.append(k)
        if looks_like_a_map(objs, keys):
            inner = [v for o in objs for v in o.values()]
            parts.append("{ [key: string]: " + render(inner, ind + 1) + " }  // e.g. " + ", ".join(keys[:5]))
        else:
            lines = []
            for k in keys:
                sub = [o[k] for o in objs if k in o]
                opt = "" if len(sub) == len(objs) else "?"
                lines.append("  " * (ind + 1) + f"{k}{opt}: " + render(sub, ind + 1))
            parts.append("{\n" + "\n".join(lines) + "\n" + "  " * ind + "}")
    if arrs:
        items = [x for a in arrs for x in a]
        parts.append(f"({render(items, ind)})[]" if items else "[]")
    return " | ".join(parts)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    root = Path(argv[1])
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    print("# Swara Studio: the shape of the published data\n")
    print("Generated by `scripts/carnatic/describe_data.py` from a build of the data;")
    print("do not edit by hand. What each file is for, how to download it and how to")
    print("tell when it changed are in [API.md §2](API.md#2-the-schools-data-offline-download).\n")
    print(f"Described from data format {manifest.get('format')}, "
          f"digest `{manifest.get('digest')}`.\n")
    print("`?` marks a key not every object has. `null` in a union means the key is")
    print("present with no value: show nothing for it.\n")
    for name in FILES:
        path = root / name
        if not path.is_file():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        print(f"## {name}\n")
        print("```ts")
        print(render([data], 0))
        print("```\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
