"""link taxonomy and tool pages

Revision ID: 614480afef20
Revises: 2970bc920e05
Create Date: 2026-08-24 10:12:56.849300
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '614480afef20'
down_revision: Union[str, None] = '2970bc920e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_locale'), 'tool', ['locale'], unique=False)
    op.create_index(op.f('ix_tool_slug'), 'tool', ['slug'], unique=True)
    op.add_column('social_link', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_social_link_category'), 'social_link', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_link_category'), table_name='social_link')
    op.drop_column('social_link', 'category')
    op.drop_index(op.f('ix_tool_slug'), table_name='tool')
    op.drop_index(op.f('ix_tool_locale'), table_name='tool')
    op.drop_table('tool')
    # ### end Alembic commands ###
