/* Swara Studio's words: [English, Tamil, Telugu, Kannada].
 *
 * English is the written default. The Tamil drafts are the designer's (handoff
 * v1); the Telugu and Kannada drafts follow the designer's app strings where
 * those exist and are first drafts elsewhere. None has been checked by a
 * native reader: every page in those languages says so. An empty slot falls
 * back to English rather than to a guess.
 */
type Row = [en: string, ta?: string, te?: string, kn?: string];

export const STRINGS = {
  /* ── chrome ── */
  "brand.name": ["Swara Studio"],
  "brand.desc": ["Carnatic music school", "கர்நாடக இசைப் பள்ளி", "కర్ణాటక సంగీత పాఠశాల", "ಕರ್ನಾಟಕ ಸಂಗೀತ ಶಾಲೆ"],
  "nav.learn": ["Learn", "கற்க", "నేర్చుకో", "ಕಲಿಯಿರಿ"],
  "nav.practice": ["Practice", "பயிற்சி", "అభ్యాసం", "ಅಭ್ಯಾಸ"],
  "nav.compose": ["Compose", "இசையமைக்க", "రచన", "ರಚನೆ"],
  "nav.listen": ["Listen", "கேட்க", "వినండి", "ಕೇಳಿ"],
  "nav.journal": ["Journal", "இதழ்", "పత్రిక", "ಪತ್ರಿಕೆ"],
  "nav.support": ["Support", "ஆதரவு", "మద్దతు", "ಬೆಂಬಲ"],
  "nav.aria": ["Swara Studio"],
  "nav.languages": ["Language", "மொழி", "భాష", "ಭಾಷೆ"],
  "unverified": ["unverified"],
  "unverified.title": ["Not yet checked by a native reader"],
  "unverified.lang": ["Translation not yet checked by a native reader"],
  "crumb.learn": ["Learn", "கற்க", "నేర్చుకో", "ಕಲಿಯಿರಿ"],
  "crumb.practice": ["Practice", "பயிற்சி", "అభ్యాసం", "ಅಭ್ಯಾಸ"],
  "crumb.compose": ["Compose", "இசையமைக்க", "రచన", "ರಚನೆ"],
  "crumb.ragas": ["Ragas", "ராகங்கள்", "రాగాలు", "ರಾಗಗಳು"],
  "crumb.talas": ["Tala library", "தாள நூலகம்", "తాళ గ్రంథాలయం", "ತಾಳ ಗ್ರಂಥಾಲಯ"],
  "crumb.talasShort": ["Talas", "தாளங்கள்", "తాళాలు", "ತಾಳಗಳು"],
  "crumb.instruments": ["Instruments", "வாத்தியங்கள்", "వాద్యాలు", "ವಾದ್ಯಗಳು"],
  "crumb.lessons": ["Lessons", "பாடங்கள்", "పాఠాలు", "ಪಾಠಗಳು"],
  "crumb.breadcrumb": ["Breadcrumb"],
  "data.absentH": ["The school's data is not loaded yet", "பள்ளியின் தரவு இன்னும் ஏற்றப்படவில்லை", "పాఠశాల సమాచారం ఇంకా లోడ్ కాలేదు", "ಶಾಲೆಯ ಮಾಹಿತಿ ಇನ್ನೂ ಲೋಡ್ ಆಗಿಲ್ಲ"],
  "data.absentP": ["The ragas, talas and lessons are published separately from the site and have not arrived here yet. The drone and the tuner work without them."],

  /* ── landing ── */
  "landing.title": ["Swara Studio · Carnatic music school"],
  "landing.meta": ["Carnatic music from the first Sa: ragas, talas and your instrument in the order musicians learn them, with a just-intonation drone, a tuner that reads swaras, a tala trainer and the beginner path. Free, no account needed."],
  "landing.eyebrow": ["Carnatic music school", "கர்நாடக இசைப் பள்ளி", "కర్ణాటక సంగీత పాఠశాల", "ಕರ್ನಾಟಕ ಸಂಗೀತ ಶಾಲೆ"],
  "landing.h1": ["Carnatic music, from the first Sa", "முதல் ஸ-விலிருந்து கர்நாடக இசை", "మొదటి స నుండి కర్ణాటక సంగీతం", "ಮೊದಲ ಸ ದಿಂದ ಕರ್ನಾಟಕ ಸಂಗೀತ"],
  "landing.lede": [
    "Ragas, talas and your instrument, taught in the order musicians learn them. The tools are free and work offline in the app. Lessons are by Shruti Swara, who plays the Carnatic flute.",
    "ராகங்கள், தாளங்கள், உங்கள் வாத்தியம் — இசைக்கலைஞர்கள் கற்கும் வரிசையில். கருவிகள் இலவசம், செயலியில் இணையம் இல்லாமலும் இயங்கும். பாடங்களை கர்நாடகப் புல்லாங்குழல் வாசிக்கும் ஷ்ருதி ஸ்வரா வழங்குகிறார்.",
    "రాగాలు, తాళాలు, మీ వాద్యం — సంగీతకారులు నేర్చుకునే క్రమంలో. సాధనాలు ఉచితం, యాప్‌లో ఆఫ్‌లైన్‌లోనూ పనిచేస్తాయి. పాఠాలు కర్ణాటక వేణువు వాయించే శ్రుతి స్వర చెబుతారు.",
    "ರಾಗಗಳು, ತಾಳಗಳು, ನಿಮ್ಮ ವಾದ್ಯ — ಸಂಗೀತಗಾರರು ಕಲಿಯುವ ಕ್ರಮದಲ್ಲಿ. ಸಾಧನಗಳು ಉಚಿತ, ಆ್ಯಪ್‌ನಲ್ಲಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲೂ ಕೆಲಸ ಮಾಡುತ್ತವೆ. ಪಾಠಗಳನ್ನು ಕರ್ನಾಟಕ ಕೊಳಲು ನುಡಿಸುವ ಶ್ರುತಿ ಸ್ವರ ಹೇಳಿಕೊಡುತ್ತಾರೆ.",
  ],
  "landing.start": ["Start here", "இங்கே தொடங்குங்கள்", "ఇక్కడ మొదలుపెట్టండి", "ಇಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ"],
  "landing.tuner": ["Open the tuner", "ஸ்ருதி கருவியைத் திறக்கவும்", "ట్యూనర్ తెరవండి", "ಟ್ಯೂನರ್ ತೆರೆಯಿರಿ"],
  "landing.firstLine": ["Your first line · sarali varisai 1", "உங்கள் முதல் வரி · சரளி வரிசை 1", "మీ మొదటి పంక్తి · సరళి వరుస 1", "ನಿಮ್ಮ ಮೊದಲ ಸಾಲು · ಸರಳೆ ವರಿಸೆ 1"],
  "landing.whoH": ["Who it is for", "யாருக்காக", "ఎవరి కోసం", "ಯಾರಿಗಾಗಿ"],
  "landing.who1h": ["Complete beginners", "முற்றிலும் புதியவர்கள்", "పూర్తిగా కొత్తవారు", "ಸಂಪೂರ್ಣ ಆರಂಭಿಕರು"],
  "landing.who1p": ["No reading and no teacher needed yet. Start with Sa, the drone and sarali varisai 1.", "குறிப்பு படிக்கத் தெரியாவிட்டாலும், ஆசிரியர் இல்லாவிட்டாலும் சரி. ஸ, ஸ்ருதி, சரளி வரிசை 1 இலிருந்து தொடங்குங்கள்.", "స్వరలిపి చదవడం, గురువు ఇంకా అవసరం లేదు. స, శ్రుతి, సరళి వరుస 1 తో మొదలుపెట్టండి.", "ಸ್ವರಲಿಪಿ ಓದುವುದು, ಗುರು ಇನ್ನೂ ಬೇಕಿಲ್ಲ. ಸ, ಶ್ರುತಿ ಮತ್ತು ಸರಳೆ ವರಿಸೆ 1 ರಿಂದ ಪ್ರಾರಂಭಿಸಿ."],
  "landing.who2h": ["Students with a teacher", "ஆசிரியரிடம் கற்பவர்கள்", "గురువు వద్ద నేర్చుకునేవారు", "ಗುರುವಿನ ಬಳಿ ಕಲಿಯುವವರು"],
  "landing.who2p": ["Practise between classes with the drone, the tala and notation at three speeds.", "வகுப்புகளுக்கு இடையே ஸ்ருதி, தாளம், மூன்று காலங்களில் குறிப்புடன் பயிற்சி செய்யுங்கள்.", "తరగతుల మధ్య శ్రుతి, తాళం, మూడు కాలాల స్వరలిపితో అభ్యాసం చేయండి.", "ತರಗತಿಗಳ ನಡುವೆ ಶ್ರುತಿ, ತಾಳ ಮತ್ತು ಮೂರು ಕಾಲಗಳ ಸ್ವರಲಿಪಿಯೊಂದಿಗೆ ಅಭ್ಯಾಸ ಮಾಡಿ."],
  "landing.who3h": ["Musicians from other traditions", "பிற இசை மரபுகளின் கலைஞர்கள்", "ఇతర సంప్రదాయాల సంగీతకారులు", "ಇತರ ಸಂಪ್ರದಾಯಗಳ ಸಂಗೀತಗಾರರು"],
  "landing.who3p": ["Hear how a raga differs from a scale, and why gamakas carry it.", "ராகம் ஒரு ஸ்வர வரிசையிலிருந்து எப்படி வேறுபடுகிறது, கமகங்கள் ஏன் அதைச் சுமக்கின்றன என்பதைக் கேளுங்கள்.", "రాగం ఒక స్వర వరుస నుండి ఎలా వేరో, గమకాలు దాన్ని ఎందుకు మోస్తాయో వినండి.", "ರಾಗವು ಸ್ವರ ಶ್ರೇಣಿಯಿಂದ ಹೇಗೆ ಭಿನ್ನ, ಗಮಕಗಳು ಅದನ್ನು ಏಕೆ ಹೊರುತ್ತವೆ ಎಂಬುದನ್ನು ಕೇಳಿ."],
  "landing.pathEyebrow": ["Start here", "இங்கே தொடங்குங்கள்", "ఇక్కడ మొదలుపెట్టండి", "ಇಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ"],
  "landing.pathH": ["The beginner path", "தொடக்கப் பாதை", "ప్రారంభ మార్గం", "ಆರಂಭಿಕ ಮಾರ್ಗ"],
  "landing.pathP": [
    "Fifty exercises and geethams, in the order they are traditionally taught. Each one plays along with the drone and the tala, at three speeds, with a view for your instrument.",
    "ஐம்பது பயிற்சிகளும் கீதங்களும், மரபாகக் கற்பிக்கப்படும் வரிசையில். ஒவ்வொன்றும் ஸ்ருதி, தாளத்துடன் மூன்று காலங்களில், உங்கள் வாத்தியத்திற்கான காட்சியுடன் இசைக்கும்.",
    "యాభై అభ్యాసాలు, గీతాలు, సంప్రదాయంగా నేర్పే క్రమంలో. ప్రతి ఒక్కటీ శ్రుతి, తాళంతో మూడు కాలాల్లో, మీ వాద్యానికి తగిన దృశ్యంతో వినిపిస్తుంది.",
    "ಐವತ್ತು ಅಭ್ಯಾಸಗಳು ಮತ್ತು ಗೀತೆಗಳು, ಸಾಂಪ್ರದಾಯಿಕವಾಗಿ ಕಲಿಸುವ ಕ್ರಮದಲ್ಲಿ. ಪ್ರತಿಯೊಂದೂ ಶ್ರುತಿ, ತಾಳದೊಂದಿಗೆ ಮೂರು ಕಾಲಗಳಲ್ಲಿ, ನಿಮ್ಮ ವಾದ್ಯದ ನೋಟದೊಂದಿಗೆ ನುಡಿಯುತ್ತದೆ.",
  ],
  "landing.begin": ["Begin sarali varisai 1", "சரளி வரிசை 1 ஐத் தொடங்குங்கள்", "సరళి వరుస 1 మొదలుపెట్టండి", "ಸರಳೆ ವರಿಸೆ 1 ಪ್ರಾರಂಭಿಸಿ"],
  "landing.noAccount": ["No account needed. Sign in only to keep your progress across devices.", "கணக்கு தேவையில்லை. சாதனங்களுக்கிடையே முன்னேற்றத்தை வைத்திருக்க மட்டும் உள்நுழையுங்கள்.", "ఖాతా అవసరం లేదు. పరికరాల మధ్య పురోగతిని ఉంచుకోవడానికి మాత్రమే సైన్ ఇన్ చేయండి.", "ಖಾತೆ ಬೇಕಿಲ್ಲ. ಸಾಧನಗಳ ನಡುವೆ ಪ್ರಗತಿಯನ್ನು ಉಳಿಸಲು ಮಾತ್ರ ಸೈನ್ ಇನ್ ಮಾಡಿ."],
  "landing.toolsH": ["Free tools", "இலவசக் கருவிகள்", "ఉచిత సాధనాలు", "ಉಚಿತ ಸಾಧನಗಳು"],
  "landing.toolsP": ["Free on the web, and offline in the app without an account.", "இணையத்தில் இலவசம்; செயலியில் கணக்கு இல்லாமல் இணையமின்றி இயங்கும்.", "వెబ్‌లో ఉచితం; యాప్‌లో ఖాతా లేకుండా ఆఫ్‌లైన్‌లో.", "ವೆಬ್‌ನಲ್ಲಿ ಉಚಿತ; ಆ್ಯಪ್‌ನಲ್ಲಿ ಖಾತೆ ಇಲ್ಲದೆ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ."],
  "landing.tool1h": ["Tuner and drone", "ஸ்ருதி கருவியும் தம்புராவும்", "ట్యూనర్, శ్రుతి", "ಟ್ಯೂನರ್ ಮತ್ತು ಶ್ರುತಿ"],
  "landing.tool1p": ["A tanpura in just intonation, and a pitch meter that reads in swaras relative to your Sa.", "இயல் சுருதியில் தம்புரா, உங்கள் ஸ-வைச் சார்ந்து ஸ்வரங்களில் காட்டும் சுருதி அளவி."],
  "landing.tool2h": ["Tala trainer", "தாளப் பயிற்சி", "తాళ అభ్యాసం", "ತಾಳ ಅಭ್ಯಾಸ"],
  "landing.tool2p": ["Watch the hand, count along, then tap the claps. Adi, rupaka, the chapu talas and all 35 suladi talas.", "கையைப் பாருங்கள், கூடவே எண்ணுங்கள், பின் தட்டுங்கள். ஆதி, ரூபகம், சாபு தாளங்கள், 35 சூளாதி தாளங்கள்."],
  "landing.tool3h": ["Raga explorer", "ராக ஆய்வு", "రాగ అన్వేషణ", "ರಾಗ ಅನ್ವೇಷಣೆ"],
  "landing.tool3p": ["Every raga page leads with its characteristic phrases, not its scale.", "ஒவ்வொரு ராகப் பக்கமும் அதன் ஸ்வர வரிசையால் அல்ல, சிறப்புப் பிரயோகங்களால் தொடங்குகிறது."],
  "landing.tool3spec": ["{m} melakartas · {r} ragas", "{m} மேளகர்த்தா · {r} ராகங்கள்", "{m} మేళకర్తలు · {r} రాగాలు", "{m} ಮೇಳಕರ್ತಗಳು · {r} ರಾಗಗಳು"],
  "landing.tool4h": ["Instruments", "வாத்தியங்கள்", "వాద్యాలు", "ವಾದ್ಯಗಳು"],
  "landing.tool4p": ["Where every swara lives on your instrument, drawn for your Sa.", "ஒவ்வொரு ஸ்வரமும் உங்கள் வாத்தியத்தில் எங்கே இருக்கிறது, உங்கள் ஸ-வுக்கு ஏற்ப வரையப்பட்டது."],
  "landing.tool4spec": ["venu · veena · violin · mridangam · voice", "வேணு · வீணை · வயலின் · மிருதங்கம் · குரல்", "వేణువు · వీణ · వయొలిన్ · మృదంగం · గాత్రం", "ಕೊಳಲು · ವೀಣೆ · ಪಿಟೀಲು · ಮೃದಂಗ · ಗಾಯನ"],
  "landing.tool5h": ["Gamaka library", "கமக நூலகம்", "గమక గ్రంథాలయం", "ಗಮಕ ಗ್ರಂಥಾಲಯ"],
  "landing.tool5p": ["Each gamaka as a pitch curve you can hear, and how it is made on your instrument.", "ஒவ்வொரு கமகமும் கேட்கக்கூடிய சுருதி வளைவாக, உங்கள் வாத்தியத்தில் அது எப்படி உருவாகிறது என்பதுடன்."],
  "landing.tool5spec": ["kampita · jaru · nokku", "கம்பிதம் · ஜாரு · நோக்கு"],
  "landing.tool6h": ["Quizzes", "வினாடி வினா", "ప్రశ్నలు", "ರಸಪ್ರಶ್ನೆ"],
  "landing.tool6p": ["Swaras by ear, ragas from a phrase, tala counting and fingering.", "காதால் ஸ்வரம், பிரயோகத்திலிருந்து ராகம், தாள எண்ணிக்கை, விரலமைப்பு."],
  "landing.tool6spec": ["by ear · by phrase", "காதால் · பிரயோகத்தால்"],
  "landing.welcomeEyebrow": ["A note from your teacher", "உங்கள் ஆசிரியரிடமிருந்து", "మీ గురువు నుండి", "ನಿಮ್ಮ ಗುರುವಿನಿಂದ"],
  "landing.welcome": [
    "I’m Shruti Swara. I play the Carnatic flute, and I built Swara Studio as the practice room I wanted when I started: a drone that is always in tune, a tala you can see, and notation that shows the gamakas instead of hiding them. Where teachers and books disagree, I’ll tell you, and show you both.",
    "நான் ஷ்ருதி ஸ்வரா. நான் கர்நாடகப் புல்லாங்குழல் வாசிக்கிறேன். நான் தொடங்கியபோது விரும்பிய பயிற்சி அறையாக ஸ்வர ஸ்டுடியோவை உருவாக்கினேன்: எப்போதும் சுருதியில் இருக்கும் தம்புரா, கண்ணால் பார்க்கக்கூடிய தாளம், கமகங்களை மறைக்காமல் காட்டும் குறிப்பு. ஆசிரியர்களும் நூல்களும் வேறுபடும் இடங்களில், அதைச் சொல்லி இரண்டையும் காட்டுவேன்.",
  ],
  "landing.portrait": ["/brand/avatar-square.png"],
  "landing.portraitAlt": ["Shruti Swara, the teacher"],
  "landing.portraitCaption": ["Shruti Swara · venu"],
  "landing.classesH": ["Learn alone, or in a class", "தனியாகவோ, வகுப்பிலோ கற்கலாம்", "ఒంటరిగా లేదా తరగతిలో నేర్చుకోండి", "ಒಬ್ಬರೇ ಅಥವಾ ತರಗತಿಯಲ್ಲಿ ಕಲಿಯಿರಿ"],
  "landing.classesP": ["Self-paced lessons and my live classes share one catalogue. Filter by format; every live class links to the lessons it builds on.", "சுயவேகப் பாடங்களும் என் நேரடி வகுப்புகளும் ஒரே பட்டியலில். வடிவத்தால் வடிகட்டுங்கள்; ஒவ்வொரு நேரடி வகுப்பும் அதற்கு அடிப்படையான பாடங்களுடன் இணைக்கப்பட்டுள்ளது."],
  "landing.supportH": ["Free to use, kept going by supporters", "பயன்படுத்த இலவசம், ஆதரவாளர்களால் தொடர்கிறது", "వాడటానికి ఉచితం, మద్దతుదారులతో నడుస్తుంది", "ಬಳಸಲು ಉಚಿತ, ಬೆಂಬಲಿಗರಿಂದ ನಡೆಯುತ್ತದೆ"],
  "landing.supportP": ["Swaras, the people who support Shruti's work, keep the school free for everyone. A Swaras supporter can add more parts to each song in the composer.", "ஷ்ருதியின் பணியை ஆதரிக்கும் ஸ்வராக்கள் பள்ளியை அனைவருக்கும் இலவசமாக வைத்திருக்கிறார்கள். ஸ்வரா ஆதரவாளர்கள் இசையமைப்பில் ஒவ்வொரு பாடலுக்கும் கூடுதல் பகுதிகளைச் சேர்க்கலாம்."],
  "landing.supportCta": ["Support Swara Studio", "ஸ்வர ஸ்டுடியோவை ஆதரியுங்கள்", "స్వర స్టూడియోకు మద్దతు ఇవ్వండి", "ಸ್ವರ ಸ್ಟುಡಿಯೋವನ್ನು ಬೆಂಬಲಿಸಿ"],
  "landing.thanks": ["Thank you. You are a Swaras supporter, and every tool here is open to you.", "நன்றி. நீங்கள் ஸ்வரா ஆதரவாளர்; இங்குள்ள ஒவ்வொரு கருவியும் உங்களுக்குத் திறந்திருக்கிறது."],
  "landing.journalH": ["From the journal", "இதழிலிருந்து", "పత్రిక నుండి", "ಪತ್ರಿಕೆಯಿಂದ"],
  "landing.journalEmpty": ["Essays on ragas, talas and tuning will appear here as they are written.", "ராகங்கள், தாளங்கள், சுருதி பற்றிய கட்டுரைகள் எழுதப்படும்போது இங்கே தோன்றும்."],
  "landing.journalAll": ["Read the journal"],
  "landing.foot": ["Swara Studio is the Carnatic music school of shrutivtuber.com.", "ஸ்வர ஸ்டுடியோ, shrutivtuber.com இன் கர்நாடக இசைப் பள்ளி.", "స్వర స్టూడియో shrutivtuber.com యొక్క కర్ణాటక సంగీత పాఠశాల.", "ಸ್ವರ ಸ್ಟುಡಿಯೋ shrutivtuber.com ನ ಕರ್ನಾಟಕ ಸಂಗೀತ ಶಾಲೆ."],

  /* ── the path's sets ── */
  "set.sarali_varisai": ["Sarali varisai", "சரளி வரிசை", "సరళి వరుస", "ಸರಳೆ ವರಿಸೆ"],
  "set.janta_varisai": ["Janta varisai", "ஜண்டை வரிசை", "జంట వరుస", "ಜಂಟಿ ವರಿಸೆ"],
  "set.dhatu_varisai": ["Dhatu varisai", "தாட்டு வரிசை", "దాటు వరుస", "ದಾಟು ವರಿಸೆ"],
  "set.sthayi": ["Tara and mandra sthayi", "தாரஸ்தாயி, மந்த்ரஸ்தாயி", "తార, మంద్ర స్థాయి", "ತಾರ ಮತ್ತು ಮಂದ್ರ ಸ್ಥಾಯಿ"],
  "set.tara_sthayi_varisai": ["Tara sthayi", "தாரஸ்தாயி", "తార స్థాయి", "ತಾರ ಸ್ಥಾಯಿ"],
  "set.mandra_sthayi_varisai": ["Mandra sthayi", "மந்த்ரஸ்தாயி", "మంద్ర స్థాయి", "ಮಂದ್ರ ಸ್ಥಾಯಿ"],
  "set.alankaram": ["Alankarams", "அலங்காரங்கள்", "అలంకారాలు", "ಅಲಂಕಾರಗಳು"],
  "set.geethams": ["Geethams", "கீதங்கள்", "గీతాలు", "ಗೀತೆಗಳು"],
  "set.geethamsNote": ["Malahari first", "மலஹரி முதலில்", "మలహరి ముందు", "ಮಲಹರಿ ಮೊದಲು"],
  "set.varnams": ["Varnams", "வர்ணங்கள்", "వర్ణాలు", "ವರ್ಣಗಳು"],

  /* ── explorer ── */
  "ragas.title": ["Ragas", "ராகங்கள்", "రాగాలు", "ರಾಗಗಳು"],
  "ragas.meta": ["All 72 melakartas and the janya ragas that grow from them. Every raga page leads with its characteristic phrases; scripts in Tamil, Telugu and Kannada."],
  "ragas.lede": ["The 72 melakartas and the janya ragas that grow from them. Every raga page leads with its phrases.", "72 மேளகர்த்தாக்களும் அவற்றிலிருந்து பிறக்கும் ஜன்ய ராகங்களும். ஒவ்வொரு ராகப் பக்கமும் அதன் பிரயோகங்களால் தொடங்குகிறது."],
  "ragas.search": ["Search ragas", "ராகங்களைத் தேடுக", "రాగాలను వెతకండి", "ರಾಗಗಳನ್ನು ಹುಡುಕಿ"],
  "ragas.searchPh": ["Name, spelling or script: Todi, Thodi, மோகனம்", "பெயர், எழுத்துக்கூட்டல் அல்லது எழுத்து: Todi, Thodi, மோகனம்"],
  "ragas.viewMela": ["Melakarta grid", "மேளகர்த்தா அட்டவணை", "మేళకర్త పట్టిక", "ಮೇಳಕರ್ತ ಪಟ್ಟಿ"],
  "ragas.viewJanya": ["Janya ragas", "ஜன்ய ராகங்கள்", "జన్య రాగాలు", "ಜನ್ಯ ರಾಗಗಳು"],
  "ragas.suddha": ["Suddha madhyama · 1–36", "சுத்த மத்யமம் · 1–36"],
  "ragas.prati": ["Prati madhyama · 37–72", "ப்ரதி மத்யமம் · 37–72"],
  "ragas.gridKey": ["Dashed border: vivadi mela. Selecting a mela shows it on the right. Search dims the melas that do not match.", "கோடிட்ட எல்லை: விவாதி மேளம். ஒரு மேளத்தைத் தேர்ந்தெடுத்தால் அது வலப்புறம் காட்டப்படும்."],
  "ragas.openMela": ["Open melakarta page", "மேளகர்த்தா பக்கத்தைத் திறக்கவும்"],
  "ragas.parent": ["Parent mela", "ஜனக மேளம்"],
  "ragas.anyParent": ["Any parent", "எந்த மேளமும்"],
  "ragas.present": ["Swaras present", "இடம்பெறும் ஸ்வரங்கள்"],
  "ragas.count": ["Swaras in arohana", "ஆரோகணத்தில் ஸ்வரங்கள்"],
  "ragas.movement": ["Movement and origin", "சஞ்சாரமும் மூலமும்"],
  "ragas.vakra": ["Vakra", "வக்ரம்"],
  "ragas.hindustani": ["Hindustani-derived", "ஹிந்துஸ்தானி மூலம்"],
  "ragas.clear": ["Clear filters", "வடிகட்டிகளை நீக்கு"],
  "ragas.sort": ["Sort", "வரிசை"],
  "ragas.sortLearn": ["Learning order", "கற்கும் வரிசை"],
  "ragas.sortAz": ["A to Z", "அகர வரிசை"],
  "ragas.emptyH": ["No raga matches", "பொருந்தும் ராகம் இல்லை"],
  "ragas.emptyQ": ["Nothing matches “{q}” with these filters. Search knows most spellings, such as Todi and Thodi. Try fewer filters, or browse by parent in the grid.", "இந்த வடிகட்டிகளுடன் “{q}” க்குப் பொருத்தம் இல்லை. Todi, Thodi போன்ற பெரும்பாலான எழுத்துக்கூட்டல்களைத் தேடல் அறியும். குறைவான வடிகட்டிகளை முயலுங்கள்."],
  "ragas.emptyF": ["No raga has every swara and property you selected. Try removing a filter.", "நீங்கள் தேர்ந்த அனைத்து ஸ்வரங்களும் பண்புகளும் கொண்ட ராகம் இல்லை. ஒரு வடிகட்டியை நீக்கிப் பாருங்கள்."],
  "ragas.sampleNote": ["The {n} janya pages at launch. Learning order is editorial: T1 first pieces (Malahari, then Mohanam), T2 varnam ragas, T3 concert ragas, T4 Hindustani-derived. Search ignores spelling differences such as th/t, sh/s, aa/a and a final -am.", "தொடக்கத்தில் {n} ஜன்ய பக்கங்கள். கற்கும் வரிசை: T1 முதல் உருப்படிகள், T2 வர்ண ராகங்கள், T3 கச்சேரி ராகங்கள், T4 ஹிந்துஸ்தானி மூலம்."],
  "ragas.janyaCount": ["{n} janya ragas", "{n} ஜன்ய ராகங்கள்"],
  "ragas.melaCount": ["72 melakartas", "72 மேளகர்த்தாக்கள்"],
  "ragas.janyaPages": ["Janya pages: {list}"],
  "ragas.chakra": ["{name} chakra · {n}, position {p}"],
  "ragas.also": ["Also performed as a raga: {name}"],

  /* ── mela page ── */
  "mela.kind": ["Melakarta · {n}", "மேளகர்த்தா · {n}"],
  "mela.dikshitar": ["Dikshitar-school raga on this mela", "இந்த மேளத்தின் தீக்ஷிதர் பாணி ராகம்"],
  "mela.dikshitarNote": ["a different raga with the same swaras, not another spelling"],
  "mela.seven": ["The seven swaras", "ஏழு ஸ்வரங்கள்"],
  "mela.scale": ["Arohana and avarohana", "ஆரோகணம், அவரோகணம்"],
  "mela.ktp": ["How the number comes from the name", "பெயரிலிருந்து எண் எப்படி வருகிறது"],
  "mela.reverse": ["read right to left", "வலமிருந்து இடமாகப் படிக்கவும்"],
  "mela.ktpP": ["Katapayadi: each consonant stands for a digit. The first two syllables of the name give the number, units first.", "கடபயாதி: ஒவ்வொரு மெய்யெழுத்தும் ஓர் எண்ணைக் குறிக்கும். பெயரின் முதல் இரு அசைகள் எண்ணைத் தருகின்றன, ஒன்றாம் இடம் முதலில்."],
  "mela.janyaOf": ["Janya ragas of this mela", "இந்த மேளத்தின் ஜன்ய ராகங்கள்"],
  "mela.noJanya": ["No janya raga of this mela has a page yet."],
  "mela.place": ["Place in the system", "அமைப்பில் இடம்"],
  "mela.drone": ["Play the scale with drone", "ஸ்ருதியுடன் ஸ்வர வரிசையை வாசிக்கவும்"],
  "mela.note": ["A melakarta is a parent scale: all seven swaras, straight up and straight down. Its janya ragas are where the music lives.", "மேளகர்த்தா ஒரு தாய் ஸ்வர வரிசை: ஏழு ஸ்வரங்களும் நேராக ஏறி நேராக இறங்கும். இசை வாழ்வது அதன் ஜன்ய ராகங்களில்."],
  "mela.page": ["raga page", "ராகப் பக்கம்"],
  "mela.suddhaM": ["Suddha madhyama · 1–36"],
  "mela.pratiM": ["Prati madhyama · 37–72"],
  "mela.vivadi": ["Vivadi: {pairs}. The second note of each pair sits on the next swara's place."],

  /* ── raga page ── */
  "raga.kindJanya": ["Janya raga", "ஜன்ய ராகம்", "జన్య రాగం", "ಜನ್ಯ ರಾಗ"],
  "raga.kindMela": ["Melakarta raga", "மேளகர்த்தா ராகம்", "మేళకర్త రాగం", "ಮೇಳಕರ್ತ ರಾಗ"],
  "raga.script": ["Swara script", "ஸ்வர எழுத்து", "స్వర లిపి", "ಸ್ವರ ಲಿಪಿ"],
  "raga.drone": ["Play with drone", "ஸ்ருதியுடன் வாசிக்கவும்", "శ్రుతితో వాయించండి", "ಶ್ರುತಿಯೊಂದಿಗೆ ನುಡಿಸಿ"],
  "raga.dronePlaying": ["Stop the drone", "ஸ்ருதியை நிறுத்து"],
  "raga.phrases": ["Characteristic phrases", "சிறப்புப் பிரயோகங்கள்", "ప్రత్యేక ప్రయోగాలు", "ವಿಶಿಷ್ಟ ಪ್ರಯೋಗಗಳು"],
  "raga.cited": ["cited · {who}", "ஆதாரங்களுடன் · {who}"],
  "raga.play": ["Play with drone", "ஸ்ருதியுடன் வாசிக்கவும்"],
  "raga.gamaka": ["Gamaka character", "கமகத் தன்மை", "గమక స్వభావం", "ಗಮಕ ಸ್ವಭಾವ"],
  "raga.scale": ["Summary scale", "சுருக்க ஸ்வர வரிசை", "సారాంశ స్వర క్రమం", "ಸಾರಾಂಶ ಸ್ವರ ಕ್ರಮ"],
  "raga.aro": ["Arohana", "ஆரோகணம்", "ఆరోహణ", "ಆರೋಹಣ"],
  "raga.ava": ["Avarohana", "அவரோகணம்", "అవరోహణ", "ಅವರೋಹಣ"],
  "raga.roles": ["Swaras with a role", "சிறப்புப் பங்குள்ள ஸ்வரங்கள்"],
  "raga.notShown": ["Not shown", "காட்டப்படவில்லை"],
  "raga.jiva": ["Jiva", "ஜீவ"],
  "raga.nyasa": ["Nyasa", "நியாச"],
  "raga.graha": ["Graha", "கிரஹ"],
  "raga.variants": ["Variants and disagreements", "வேறுபாடுகளும் கருத்து வேற்றுமைகளும்"],
  "raga.noVariants": ["No recorded variants. Sources agree on this raga’s swaras and movement.", "பதிவான வேறுபாடுகள் இல்லை. இந்த ராகத்தின் ஸ்வரங்களிலும் சஞ்சாரத்திலும் ஆதாரங்கள் ஒத்துப்போகின்றன."],
  "raga.comps": ["Well-known compositions for learners", "கற்போருக்கான பிரபல உருப்படிகள்"],
  "raga.noComps": ["No compositions are listed for this raga yet."],
  "raga.recording": ["Reference recording", "மாதிரிப் பதிவு"],
  "raga.recordingP": ["Slot for Shruti Swara’s own recording, added later. Until then, the play buttons use the synthesised drone and voice.", "ஷ்ருதி ஸ்வராவின் சொந்தப் பதிவுக்கான இடம், பின்னர் சேர்க்கப்படும். அதுவரை, இசை பொத்தான்கள் செயற்கை ஸ்ருதியையும் குரலையும் பயன்படுத்தும்."],
  "raga.tradition": ["About this raga’s tradition", "இந்த ராகத்தின் மரபு பற்றி"],
  "raga.traditional": ["traditional", "மரபுவழி"],
  "raga.traditionPrefix": ["Traditional attribution: {text}"],
  "raga.parent": ["Parent melakarta", "ஜனக மேளகர்த்தா"],
  "raga.related": ["Related ragas", "தொடர்புடைய ராகங்கள்"],
  "raga.sources": ["Sources and confidence", "ஆதாரங்களும் நம்பகத்தன்மையும்"],
  "raga.high": ["High confidence: the sources agree.", "உயர் நம்பகத்தன்மை: ஆதாரங்கள் ஒத்துப்போகின்றன."],
  "raga.sourceNote": ["Every field on this page is cited. Nothing here is from a single teacher’s lineage alone.", "இப்பக்கத்தின் ஒவ்வொரு தகவலுக்கும் ஆதாரம் உண்டு. எதுவும் ஒரு ஆசிரியரின் பரம்பரையிலிருந்து மட்டும் அல்ல."],
  "raga.viewSources": ["View sources", "ஆதாரங்களைக் காண்க"],
  "raga.hideSources": ["Hide sources"],
  "raga.journal": ["From the journal", "இதழிலிருந்து"],
  "raga.common": ["Common practice", "பொது வழக்கு"],
  "raga.some": ["Some schools", "சில பாணிகள்"],
  "raga.shown": ["shown", "காட்டப்படுகிறது"],
  "raga.key": ["Underlined in rose: vakra (zigzag) movement. Marked \"anya\": a swara from outside the parent mela.", "ரோஸ் அடிக்கோடு: வக்ர சஞ்சாரம். \"anya\": ஜனக மேளத்திற்கு வெளியிலிருந்து வரும் ஸ்வரம்."],
  "raga.anya": ["anya"],
  "raga.anyaTag": ["anya swara {s}", "அன்ய ஸ்வரம் {s}"],
  "raga.tierFirst": ["first pieces", "முதல் உருப்படிகள்"],
  "raga.tierLater": ["for later", "பின்னர் கற்க"],
  "raga.hindustaniTag": ["Hindustani-derived, often heard in tukkadas"],
  "raga.noPhrases": ["No characteristic phrases are sourced for this raga yet; the summary scale is below."],
  "raga.characterFrom": ["{who}"],
  "raga.parentAlt": ["Some treatises place {name} under mela {list}."],
  "raga.alternativeParents": ["Other classifications"],
  "raga.disagreements": ["Where sources disagree"],
  "raga.someSources": ["Some sources"],
  "raga.hindustaniCompare": ["Hindustani counterpart"],
  "raga.oneSource": ["one source"],
  "raga.mostSources": ["most sources"],
  "raga.sourcesAgree": ["sources agree"],
  "raga.disputed": ["Disputed"],
  "raga.otherScripts": ["Other scripts"],
  "raga.melaLink": ["Melakarta {n} · {name}"],
  "raga.sameAsMela": ["This melakarta is also sung as a raga. Its scale page, with the katapayadi, is {link}."],
  "raga.pageLater": ["page later", "பக்கம் பின்னர்"],

  /* ── confidence ── */
  "conf.medium": ["Some sources differ", "சில ஆதாரங்கள் வேறுபடுகின்றன"],
  "conf.low": ["One source; check with a teacher", "ஒரு ஆதாரம்; ஆசிரியரிடம் சரிபார்க்கவும்"],
  "conf.sources": ["Sources"],

  /* ── drone ── */
  "drone.eyebrow": ["Drone", "தம்புரா", "శ్రుతి", "ಶ್ರುತಿ"],
  "drone.on": ["Drone on", "தம்புரா இயக்கு", "శ్రుతి ఆన్", "ಶ್ರುತಿ ಆನ್"],
  "drone.off": ["Drone off", "தம்புரா நிறுத்து", "శ్రుతి ఆఫ్", "ಶ್ರುತಿ ಆಫ್"],
  "drone.tuning": ["Tuning"],
  "drone.pa": ["Pa–Sa–Sa–Sa"],
  "drone.ma": ["Ma–Sa–Sa–Sa"],
  "drone.ni": ["Ni–Sa–Sa–Sa"],
  "drone.mute": ["Mute Pa"],
  "drone.paNote": ["Default, for every raga that has Pa."],
  "drone.maNote": ["The common tuning for ragas without Pa."],
  "drone.niNote": ["Advanced: mostly Hindustani."],
  "drone.muteNote": ["For ragas with M₂ and no Pa, and a conservative choice for ragas without Pa."],
  "drone.sa": ["Your Sa"],
  "drone.ji": ["Just intonation relative to Sa. Textbook just-intonation values; performers vary."],
  "drone.volume": ["Volume"],
  "drone.miniStop": ["Stop"],

  /* ── generic ── */
  "gen.signIn": ["Sign in", "உள்நுழைக", "సైన్ ఇన్", "ಸೈನ್ ಇನ್"],
  "gen.free": ["free"],
  "gen.coming": ["coming"],
  "gen.speed": ["Speed {n}"],
  "gen.counts": ["{n} counts"],
  "gen.exercises": ["{n} exercises"],
  "gen.of": ["{a} of {b}"],
  "gen.loading": ["Loading…"],
  "gen.play": ["Play"],
  "gen.pause": ["Pause"],
  "gen.stop": ["Stop"],
  "gen.close": ["Close"],
  "gen.save": ["Save"],
  "gen.saved": ["Saved"],
  "gen.next": ["Next"],
  "gen.previous": ["Previous"],
  "gen.all": ["All", "அனைத்தும்"],
} satisfies Record<string, Row>;

export type Key = keyof typeof STRINGS;
