# SPDX-License-Identifier: AGPL-3.0-only
"""
Serving uploaded media that lives in R2.

Only reached when R2 is configured and no public base is set. With a public
base — a custom domain, or Cloudflare's r2.dev — the markup points straight at
it and this route is never asked. With no R2 at all, Caddy serves `/media/`
from disk and this route is never asked either.

**It exists because the middle case was broken.** R2 configured without a
public base stored the file in the bucket and handed back `/media/<name>`,
which is Caddy reading local disk, where the file is not. Every uploaded image
would have 404'd while the database row looked perfectly correct.

Serving through the site rather than r2.dev is the better shape regardless:
one origin instead of a third-party hostname in the markup, nothing depending
on a dashboard toggle somebody has to find, and r2.dev is rate-limited and
documented as unsuitable for production. The site already sits behind
Cloudflare, so the caching that mattered is still there.
"""
from __future__ import annotations

import re

from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select
from fastapi import APIRouter, Depends, HTTPException, Response

from shruti.core.db import get_session
from shruti.models import Media
from shruti.core.storage import fetch, r2_configured

router = APIRouter(prefix="/api/media", tags=["media"])

# Filenames are generated by the uploader and are content-addressed. Anything
# that is not that shape is refused rather than passed to the bucket: a key
# containing `..` or a slash is how a read of one bucket becomes a read of
# somebody else's prefix.
SAFE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,180}$")


# GET and HEAD both. A HEAD that 405s where the GET succeeds confuses caches
# and link checkers, and Cloudflare sits in front of this. Starlette drops the
# body for HEAD itself, so one handler answers both correctly.
@router.api_route("/{filename}", methods=["GET", "HEAD"])
async def serve(
    filename: str, session: AsyncSession = Depends(get_session)
) -> Response:
    if not SAFE.match(filename) or ".." in filename:
        raise HTTPException(404, "no such file")
    if not r2_configured():
        # Caddy owns /media/ in this case; nothing here should answer and
        # pretend otherwise.
        raise HTTPException(404, "no such file")

    # Only actual media. The bucket also holds the files people have PAID for,
    # and a proxy that serves whatever name it is given hands those out to
    # anyone who guesses one — which is not a guess at all once a name appears
    # in a receipt or a log. So the media table is the allow-list: if it is not
    # a row here, this route does not know about it.
    known = (
        await session.execute(select(Media).where(Media.filename == filename))
    ).scalar_one_or_none()

    if known is None:
        # It may be a modern-format variant, which has no row of its own —
        # `photo.avif` beside `photo.png`. The allow-list is NOT relaxed to let
        # those through: the row is still required, and the row must itself say
        # it wrote that format. A name whose stem matches nothing, or whose
        # extension the row never recorded, is refused exactly as before.
        stem, _, ext = filename.rpartition(".")
        if stem and ext in ("avif", "webp"):
            parent = (
                await session.execute(
                    select(Media).where(Media.filename.like(f"{stem}.%"))
                )
            ).scalars().first()
            if parent is not None and ext in (parent.variants or "").split(","):
                known = parent

    if known is None:
        raise HTTPException(404, "no such file")

    got = await fetch(filename)
    if got is None:
        raise HTTPException(404, "no such file")

    data, content_type = got
    return Response(
        content=data,
        media_type=content_type,
        headers={
            # Content-addressed, so the bytes behind a URL never change.
            "Cache-Control": "public, max-age=31536000, immutable",
        },
    )
