#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""
Fetch the Tamil, Telugu and Kannada faces (and Noto Sans Math, for the
gamaka signs) that Swara Studio adds to the type stacks, and serve them from
this domain like the other five faces (tokens/fonts-local.css explains why).

    python3 frontend/site/scripts/fetch-indic-fonts.py

Keeps only each family's own script subset (and math/symbols for Noto Sans
Math): the Latin subsets are already served by EB Garamond, Commissioner and
JetBrains Mono, and the `unicode-range` blocks mean a reader of an English page
never downloads any of these. All are SIL Open Font License 1.1.
"""
import hashlib
import io
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PUBLIC = ROOT / "frontend" / "site" / "public" / "fonts"
CSS = ROOT / "frontend" / "shared" / "src" / "tokens" / "fonts-indic.css"
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

FAMILIES = [
    ("Noto Serif Tamil", "notoseriftamil", "tamil"),
    ("Noto Sans Tamil", "notosanstamil", "tamil"),
    ("Noto Serif Telugu", "notoseriftelugu", "telugu"),
    ("Noto Sans Telugu", "notosanstelugu", "telugu"),
    ("Noto Serif Kannada", "notoserifkannada", "kannada"),
    ("Noto Sans Kannada", "notosanskannada", "kannada"),
    ("Noto Sans Math", "notosansmath", "*"),
]

#: The notation signs Noto Sans Math is here for, and nothing else: the SSP
#: gamaka signs (∿ ∴ ∵ ⋎ ∧ ✓ ⌒) and the jaru strokes (╱ ╲). Subset, because
#: the whole face is half a megabyte and Google serves it without ranges.
MATH_SIGNS = "U+2227,U+2234,U+2235,U+223F,U+22CE,U+2312,U+2571,U+2572,U+2713"


def subset(data: bytes, unicodes: str) -> bytes:
    from fontTools import subset as ft
    font = ft.load_font(io.BytesIO(data), ft.Options())
    options = ft.Options()
    options.flavor = "woff2"
    s = ft.Subsetter(options)
    s.populate(unicodes=ft.parse_unicodes(unicodes))
    s.subset(font)
    out = io.BytesIO()
    ft.save_font(font, out, options)
    return out.getvalue()


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> None:
    PUBLIC.mkdir(parents=True, exist_ok=True)
    out = [
        "/* Swara Studio's faces: Tamil, Telugu and Kannada in serif and sans, and",
        " * Noto Sans Math for the gamaka signs (∿ ∴ ∵ ⋎). Served from this domain;",
        " * generated by frontend/site/scripts/fetch-indic-fonts.py — regenerate by",
        " * re-running it, not by hand. SIL Open Font License 1.1. */",
    ]
    for family, stem, wanted in FAMILIES:
        weights = "" if family == "Noto Sans Math" else ":wght@400..700"
        css = get(f"https://fonts.googleapis.com/css2?family={family.replace(' ', '+')}{weights}&display=swap").decode()
        blocks = re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, flags=re.S)
        if wanted == "*":
            blocks = [("signs", b) for b in re.findall(r"@font-face \{.*?\}", css, flags=re.S)]
        for comment, block in blocks:
            if wanted != "*" and comment not in wanted.split():
                continue
            url = re.search(r"url\((https://[^)]+)\)", block).group(1)
            data = get(url)
            if wanted == "*":
                data = subset(data, MATH_SIGNS)
                block = block.replace("}", f"  unicode-range: {MATH_SIGNS.replace(',', ', ')};\n}}")
            name = f"{stem}-{hashlib.sha256(data).hexdigest()[:8]}.woff2"
            (PUBLIC / name).write_bytes(data)
            block = block.replace(url, f"'/fonts/{name}'")
            out.append(f"/* {family} · {comment} */\n{block}")
            print(name, len(data) // 1024, "KB")
    CSS.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
